name: burst-db-env
channels:
- conda-forge
dependencies:
- python>=3.10
- click
- duckdb
- fiona
- geopandas-base
- numpy
- pandas
- pip
- pyarrow
- pyproj
- requests
- shapely
- tqdm
- utm
- pip:
  - unzip-http
